import React from 'react'
import {
  Utensils,
  Coffee,
  CupSoda,
  IceCream,
  Sandwich,
  Salad,
  Cookie,
  Cake,
  Apple,
  Pizza,
  Soup,
  Wheat,
  Drumstick,
  Dessert,
  type LucideIcon,
} from 'lucide-react'

export const CANONICAL_CATEGORY_MAP: Record<string, string> = {
  'burgers': 'Burger',
  'burger': 'Burger',
  'chinese burgers': 'Chinese Burgers',
  'sandwiches': 'Sandwich',
  'sandwich': 'Sandwich',
  'chinese sandwiches': 'Chinese Sandwiches',
  'beverages': 'Beverages',
  'drinks': 'Beverages',
  'cold beverages': 'Cold Beverages',
  'hot beverages': 'Hot Beverages',
  'fresh juice': 'Fresh Juice',
  'ice cream shakes': 'Ice Cream Shakes',
  'ice cream scoops': 'Ice Cream Scoops',
  'coolers': 'Coolers',
  'mojitos': 'Mojitos',
  'dimsums': 'Dimsums',
  'momos': 'Momos',
  'noodles': 'Noodles',
  'pasta': 'Pasta',
  'salads': 'Salads',
  'fruit salad': 'Fruit Salad',
  'tacos': 'Tacos',
  'wraps': 'Wraps',
  'sub': 'Sub',
  'waffles': 'Waffles',
  'quick bites': 'Quick Bites',
  'crispy snacks': 'Crispy Snacks',
  'street flavours': 'Street Flavours',
  'meals': 'Meals',
  'pick a meal': 'Pick A Meal',
  'wholesome meal': 'Wholesome Meal',
  'burrito bowls': 'Burrito Bowls',
  'rice': 'Rice',
  'classic indian combos': 'Classic Indian Combos',
  'continental': 'Continental',
  'soups': 'Soups',
  'dil se tandoori': 'Dil Se Tandoori',
  'paneer': 'Paneer',
  'veg': 'Veg',
  'non veg': 'Non Veg',
  'veg appetizers': 'Veg Appetizers',
  'non veg appetizers': 'Non Veg Appetizers',
  'veg kathi rolls': 'Veg Kathi Rolls',
  'non veg kathi rolls': 'Non Veg Kathi Rolls',
  'chai nagri': 'Chai Nagri',
  'chai pe charcha': 'Chai Pe Charcha',
  'maggi': 'Maggi',
  'maggi / pasta': 'Maggi / Pasta',
  'nescafé': 'Nescafé',
  'nescafe': 'Nescafé',
  'blended cold beverages & more coolers': 'Blended Cold Beverages & More Coolers',
  'cold coffee, chocolate & others': 'Cold Coffee, Chocolate & Others',
  'fries': 'Fries',
  'pastas': 'Pasta',
  'sides': 'Sides',
  'signature wraps': 'Signature Wraps',
  'thick shakes': 'Thick Shakes',
  'subs': 'Sub',
  'mocktails': 'Mocktails',
  'juices': 'Juices',
  'dosa': 'Dosa',
  'uttapam': 'Uttapam',
  'breads': 'Breads',
  'sides / snacks': 'Sides / Snacks',
  'cake (small)': 'Cake (Small)',
  'pastries (fresh cream)': 'Pastries (Fresh Cream)',
  'pastries (chocolate)': 'Pastries (Chocolate)',
  'dessert': 'Dessert',
  'savouries (veg)': 'Savouries (Veg)',
  'savouries (non veg)': 'Savouries (Non Veg)',
  'pizza': 'Pizza',
}

export function normalizeCategory(category: string | undefined | null): string {
  if (!category) return 'Other'
  const trimmed = category.trim()
  const lower = trimmed.toLowerCase()
  return CANONICAL_CATEGORY_MAP[lower] || trimmed
}

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  'Burger': Sandwich,
  'Chinese Burgers': Sandwich,
  'Sandwich': Sandwich,
  'Chinese Sandwiches': Sandwich,
  'Beverages': CupSoda,
  'Cold Beverages': CupSoda,
  'Hot Beverages': Coffee,
  'Fresh Juice': Apple,
  'Ice Cream Shakes': IceCream,
  'Ice Cream Scoops': IceCream,
  'Coolers': CupSoda,
  'Mojitos': CupSoda,
  'Dimsums': Utensils,
  'Momos': Utensils,
  'Noodles': Utensils,
  'Pasta': Utensils,
  'Salads': Salad,
  'Fruit Salad': Salad,
  'Tacos': Sandwich,
  'Wraps': Sandwich,
  'Sub': Sandwich,
  'Waffles': Dessert,
  'Quick Bites': Cookie,
  'Crispy Snacks': Cookie,
  'Street Flavours': Utensils,
  'Meals': Utensils,
  'Pick A Meal': Utensils,
  'Wholesome Meal': Utensils,
  'Burrito Bowls': Utensils,
  'Rice': Utensils,
  'Classic Indian Combos': Utensils,
  'Continental': Utensils,
  'Soups': Soup,
  'Dil Se Tandoori': Drumstick,
  'Paneer': Utensils,
  'Veg': Salad,
  'Non Veg': Drumstick,
  'Veg Appetizers': Utensils,
  'Non Veg Appetizers': Drumstick,
  'Veg Kathi Rolls': Sandwich,
  'Non Veg Kathi Rolls': Sandwich,
  'Chai Nagri': Coffee,
  'Chai Pe Charcha': Coffee,
  'Maggi': Utensils,
  'Maggi / Pasta': Utensils,
  'Nescafé': Coffee,
  'Blended Cold Beverages & More Coolers': CupSoda,
  'Cold Coffee, Chocolate & Others': CupSoda,
  'Fries': Cookie,
  'Sides': Cookie,
  'Signature Wraps': Sandwich,
  'Thick Shakes': CupSoda,
  'Mocktails': CupSoda,
  'Juices': Apple,
  'Dosa': Wheat,
  'Uttapam': Wheat,
  'Breads': Wheat,
  'Sides / Snacks': Cookie,
  'Cake (Small)': Cake,
  'Pastries (Fresh Cream)': Cake,
  'Pastries (Chocolate)': Cake,
  'Dessert': Dessert,
  'Savouries (Veg)': Salad,
  'Savouries (Non Veg)': Drumstick,
  'Snacks': Cookie,
  'Fast Food': Sandwich,
  'Desserts': Dessert,
  'Chinese': Utensils,
  'South Indian': Utensils,
  'North Indian': Utensils,
  'Pizza': Pizza,
}

export function getCategoryIcon(category?: string | null): LucideIcon {
  const norm = normalizeCategory(category)
  return CATEGORY_ICON_MAP[norm] || Utensils
}

export function CategoryIcon({
  category,
  className = 'w-4 h-4 shrink-0',
}: {
  category?: string | null
  className?: string
}) {
  const IconComponent = getCategoryIcon(category)
  return React.createElement(IconComponent, { className, 'aria-hidden': 'true' })
}
