export const CANONICAL_CATEGORY_MAP: Record<string, string> = {
  'burgers': 'Burger',
  'burger': 'Burger',
  'chinese burgers': 'Chinese Burgers',
  'sandwiches': 'Sandwich',
  'sandwich': 'Sandwich',
  'chinese sandwiches': 'Chinese Sandwiches',
  'beverages': 'Beverages',
  'drinks': 'Beverages',
  'cold beverages': 'Cold Beverages',
  'hot beverages': 'Hot Beverages',
  'fresh juice': 'Fresh Juice',
  'ice cream shakes': 'Ice Cream Shakes',
  'ice cream scoops': 'Ice Cream Scoops',
  'coolers': 'Coolers',
  'mojitos': 'Mojitos',
  'dimsums': 'Dimsums',
  'momos': 'Momos',
  'noodles': 'Noodles',
  'pasta': 'Pasta',
  'salads': 'Salads',
  'fruit salad': 'Fruit Salad',
  'tacos': 'Tacos',
  'wraps': 'Wraps',
  'sub': 'Sub',
  'waffles': 'Waffles',
  'quick bites': 'Quick Bites',
  'crispy snacks': 'Crispy Snacks',
  'street flavours': 'Street Flavours',
  'meals': 'Meals',
  'pick a meal': 'Pick A Meal',
  'wholesome meal': 'Wholesome Meal',
  'burrito bowls': 'Burrito Bowls',
  'rice': 'Rice',
  'classic indian combos': 'Classic Indian Combos',
  'continental': 'Continental',
  'soups': 'Soups',
  'dil se tandoori': 'Dil Se Tandoori',
  'paneer': 'Paneer',
  'veg': 'Veg',
  'non veg': 'Non Veg',
  'veg appetizers': 'Veg Appetizers',
  'non veg appetizers': 'Non Veg Appetizers',
  'veg kathi rolls': 'Veg Kathi Rolls',
  'non veg kathi rolls': 'Non Veg Kathi Rolls',
  'chai nagri': 'Chai Nagri',
  'chai pe charcha': 'Chai Pe Charcha',
}

export function normalizeCategory(category: string | undefined | null): string {
  if (!category) return 'Other'
  const trimmed = category.trim()
  const lower = trimmed.toLowerCase()
  return CANONICAL_CATEGORY_MAP[lower] || trimmed
}

export function getCategoryEmoji(category: string): string {
  const norm = normalizeCategory(category)
  const map: Record<string, string> = {
    'Burger': '🍔',
    'Chinese Burgers': '🍔',
    'Sandwich': '🥪',
    'Chinese Sandwiches': '🥪',
    'Beverages': '🥤',
    'Cold Beverages': '🥤',
    'Hot Beverages': '☕',
    'Fresh Juice': '🧃',
    'Ice Cream Shakes': '🥤',
    'Ice Cream Scoops': '🍨',
    'Coolers': '🧊',
    'Mojitos': '🍹',
    'Dimsums': '🥟',
    'Momos': '🥟',
    'Noodles': '🍜',
    'Pasta': '🍝',
    'Salads': '🥗',
    'Fruit Salad': '🍉',
    'Tacos': '🌮',
    'Wraps': '🌯',
    'Sub': '🥖',
    'Waffles': '🧇',
    'Quick Bites': '🍿',
    'Crispy Snacks': '🍟',
    'Street Flavours': '🥘',
    'Meals': '🍛',
    'Pick A Meal': '🍱',
    'Wholesome Meal': '🍲',
    'Burrito Bowls': '🥣',
    'Rice': '🍚',
    'Classic Indian Combos': '🍛',
    'Continental': '🍽️',
    'Soups': '🥣',
    'Dil Se Tandoori': '🍢',
    'Paneer': '🧀',
    'Veg': '🥦',
    'Non Veg': '🍗',
    'Veg Appetizers': '🥟',
    'Non Veg Appetizers': '🍗',
    'Veg Kathi Rolls': '🌯',
    'Non Veg Kathi Rolls': '🌯',
    'Chai Nagri': '☕',
    'Chai Pe Charcha': '☕',
    'Snacks': '🍿',
    'Fast Food': '🍔',
    'Desserts': '🍰',
    'Chinese': '🥡',
    'South Indian': '🥘',
    'North Indian': '🍲',
  }

  return map[norm] || '🍽️'
}
